### PR TITLE
Building with Backgrounds and Gradients

### PR DESCRIPTION
**Pull request by tiagoes**
Tiago and Grace's Building-with-background-and-gradient

screenshot

This project was the second project compiled by Grace and Tiago in the Microverse HTML/CSS section of the course work. It involved cloning an apple page.The project contains a wrapper with a background image, a slide with images and a footer. The page contains a navBar with a special background gradient color.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @GraceOyiza and @tiagoes, great job building this project :+1: Commits are descriptive :slightly_smiling_face: However, to get our project approved, we need to work on the comments below:
- Let us improve our README file, let us add instructions on how to clone the project, assuming the other person has no programming  background, let us also add our social handles to our author section
- Let us add links to our four bottom elements
li
- Let us add a link to the copyright
mi
- Kindly edit the Pull Request, add a title and a short description
pi
- Kindly implement the float property for aligning elements
fi
- Let us implement the DRY rule, we did apply it but we could do better :smile: 

[OPTIONAL]
- Kindly remove the border on the hero image

Kindly implement these changes and submit another code review :+1: 
_Happy coding_ :woman_technologist: :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by tiagoes** [comment]
All the necessaries changes have been done.
Please review our code again.

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Status: Changes required 🛑

## Hello @GraceOyiza and @tiagoes 👋! Such an impressive project you have here 🧨.

### However, we need to work on some changes before we can merge.

- Your clone needs to span the full width of the screen. Right now it has a fixed width.

#### Clone
Annotation 2020-06-30 223154

#### Original
image

- I have noticed you have added border to your `wrapper` class. If it is removed, the whole container shifts down. Please fix that.

Annotation 2020-06-30 223547

Apply these changes and request another code review.

Happy coding 👨‍💻

**Comment by tiagoes** [comment]
All the necessaries changes have been done.
Please review our code again.

Correction

**Review by rammazzoti2000 — APPROVED** [review]
### Hello @GraceOyiza :wave: 
## Project Approved :heavy_check_mark: 
Nice project, good use of HTML semantic, all changes required by previous TSEs have been implemented, the project looks professional and there is no need for further changes.
The project therefore is approved, you may merge when you feel ready.

### <em> Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of **_alexandru_** if you have any additional question)</em>
###  Status: Project Approved :heavy_check_mark:

**Pull request merged**
